module:
  imports:
    # Your block's GitHub URL (replace <USERNAME> and <COLLECTION-NAME> with your GitHub username and block collection name)
    - path: github.com/HugoBlox/hugo-blox-builder
      disable: false
    - path: github.com/HugoBlox/theme-academic-cv
      disable: false